version: "3.4"

services:

  skillhub-parsers:
    build: .
    container_name: skillhub-parsers
    tty: true
    env_file:
      - .env
    volumes:
      - ./:/app
    logging:
      options:
        max-size: "100m"
        max-file: "2"